SELECT ibq.TRADINGDAY,avg(1e8*abs(ibq.PREVCLOSEDIRTYPRICE-ibq.CLOSEDIRTYPRICE)/ibq.TRANSACTIONVOL) AS illiquidity  
FROM jy.BOND_INTERBANKQUOTE ibq
left JOIN jy.bond_code bc ON bc.INNERCODE = ibq.INNERCODE
--JOIN jy.BOND_CBVALUATION bcb ON bcb.INNERCODE = ibq.INNERCODE AND bcb.ENDDATE = ibq.TRADINGDAY
WHERE ibq.TRADINGDAY between TRUNC (SYSDATE-7) and TRUNC (SYSDATE)
AND ibq.TRANSACTIONVOL > 1e7                -- excluding tiny trades 
AND ibq.PREVCLOSEDIRTYPRICE > 0
GROUP BY  ibq.TRADINGDAY
ORDER BY  ibq.TRADINGDAY
