DATA_DIR = "D:/workspace/data"
WORD_DIR = 'D:/workspace/data/asset-class/'
ASSET_DIR = 'D:/workspace/zjsxzy_in_js/website/everyday-update/data/'
WORD_HEAT_DIR = 'D:/workspace/zjsxzy_in_js/website/word_heat/data'
TOPIC_DIR = '%s/topic'%(DATA_DIR)
WST_WORD_CNT_FILE = '%s/words/wst_word_count.pkl'%(DATA_DIR)
WST_WORD_CNT_CHECKED_FILE = '%s/words/wst_word_count_checked.txt'%(DATA_DIR)
WST_TOTAL_WORD_COUNT_FILE = "%s/words/wst_total_word_count.pkl"%(DATA_DIR)
GOV_WORD_CNT_FILE = '%s/words/gov_word_count.pkl'%(DATA_DIR)
GOV_WORD_CNT_CHECKED_FILE = '%s/words/gov_word_count_checked.txt'%(DATA_DIR)
GOV_TOTAL_WORD_COUNT_FILE = "%s/words/gov_total_word_count.pkl"%(DATA_DIR)
# WORD_COUNT_FILE = "%s/wallstreetcn_words/wallstreetcn_word_count.json"%(DATA_DIR)
# WORD_COUNT_FILE = '%s/wallstreetcn_words/word_count.pkl'%(DATA_DIR)
# TOTAL_WORD_COUNT_FILE = "%s/wallstreetcn_words/wallstreetcn_total_word_count.json"%(DATA_DIR)
# TOTAL_WORD_COUNT_FILE = "%s/wallstreetcn_words/total_word_count.pkl"%(DATA_DIR)
WALLSTCN_MODEL = "D:/workspace/model/text.model"
ASSET_CLASS_DIR = "%s/asset-class"%(DATA_DIR)
TOPIC_CLASS_DIR = '%s/topic-class'%(DATA_DIR)
TOPIC_NUMBER = 100
WORDS_FILES = '%s/words.txt'%(WORD_HEAT_DIR)
WEI_INDEX_DIR = 'D:/Data/wei_index'