# encoding: utf-8
DATA_DIR = 'D:/Data/fund'
FOF_DIR = 'D:/workspace/data/FOF'
RPT_DIR = 'D:/Data/fund/rpt'
COMP_DIR = 'D:/Data/fund/comp'
COMP_RPT_DIR = 'D:/Data/fund/comp_rpt'
INDEX_HIS_DIR = 'D:/Data/index'
INDEX_DIR = 'D:\workspace\zjsxzy_in_js\website\everyday-update\data'
stock_funds_file = u'%s/股票型基金列表.xlsx'%(DATA_DIR)
mixed_funds_file = u'%s/混合型基金列表.xlsx'%(DATA_DIR)
bond_funds_files = u'%s/债券型基金列表.xlsx'%(DATA_DIR)
LIST_DIR = 'D:/Data/list'
theme_file = u'%s/主题行业.xlsx'%(LIST_DIR)
concept_file = u'%s/概念板块.xlsx'%(LIST_DIR)
sector_file = u'%s/板块指数.xlsx'%(LIST_DIR)
rptDate = '20181231'
JY_DB_PARAM = 'DRIVER={SQL Server};SERVER=10.0.185.138;DATABASE=JYDB;UID=js_dev;PWD=js_dev'
WEBSITE_DIR = 'D:/workspace/zjsxzy_in_js/website/FOF/data'
COMP_STOCK_HOLD_DIR = 'D:/Data/fund/holding/'
